image: rocker/rstudio

test:
   script:
     - sudo apt-get update
     - sudo apt-get -y install libxml2-dev
     - Rscript -e 'install.packages(c("ggplot2", "rlang", "utils", "graphics", "stats", "devtools"), repos="https://cloud.r-project.org")'
     - R CMD build . --no-build-vignettes --no-manual
     - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
     - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
     - R -e 'devtools::test()'
